import { createHash, randomUUID } from 'node:crypto';
import { z } from 'zod';

import {
  activityTrackReadResultSchema,
  activityTrackReserveMetadataSchema,
  activityTrackRevisionSchema,
  activityTrackUploadReservationSchema,
} from '@workout/contracts/activity-tracks';
import { trackSegmentPolicySchema, trackDistancesSchema } from '@workout/contracts/tracks';

import type { Database, Transaction } from './database.js';
import { enqueue, PersistenceConflict } from './outbox.js';

const uuid = z.uuid().transform((value) => value.toLowerCase());
const idempotencyKey = z
  .string()
  .min(8)
  .max(128)
  .regex(/^[A-Za-z0-9._:-]+$/);
const failureCode = z
  .string()
  .min(1)
  .max(100)
  .regex(/^[A-Z0-9_:-]+$/);
const sha256 = z.string().regex(/^[a-f0-9]{64}$/);

const UUID_SEGMENT = '[0-9a-f-]{36}';
/**
 * Object keys are generated by the server and re-derived here before they are recorded.
 * A reference that does not name this tenant, this activity, this track, this upload and
 * the digest of the bytes just validated is refused: persistence never records a key a
 * caller handed it without rebuilding the same key itself.
 */
const FINAL_REF_PATTERN = new RegExp(
  `^private/v1/tenants/(${UUID_SEGMENT})/activities/(${UUID_SEGMENT})/tracks/(${UUID_SEGMENT})/(raw|normalized|map_path)/uploads/(${UUID_SEGMENT})/sha256/([a-f0-9]{64})[.](fit|gpx|json)$`,
);
const finalStorageRef = z.string().max(512).regex(FINAL_REF_PATTERN);

const MAX_ACTIVE_TRACK_UPLOADS = 10;
const MAX_TRACK_UPLOAD_HISTORY = 100;
const MAX_PENDING_TRACK_UPLOAD_BYTES = 128 * 1024 * 1024;
const MAX_LIVE_TRACK_BYTES = 512 * 1024 * 1024;
/**
 * Bytes a tenant may have waiting for reclamation. Deletion schedules cleanup rather than
 * performing it, so without this a loop of store-then-delete would keep passing the live
 * quota while real objects piled up behind a lagging or failing worker.
 */
const MAX_PENDING_CLEANUP_TRACK_BYTES = 512 * 1024 * 1024;
const MAX_TRACK_REVISIONS_PER_ACTIVITY = 20;
const UPLOAD_EXPIRY_MINUTES = 30;
/**
 * How long a prepared upload may keep publishing its three objects. Object cleanup defers
 * while the window is open, so it bounds how long a deletion can wait for a writer; the
 * database CHECK caps it at ten minutes past preparation.
 */
const PUBLICATION_FENCE_SECONDS = 120;

type Reservation = z.infer<typeof activityTrackUploadReservationSchema>;
type ReadResult = z.infer<typeof activityTrackReadResultSchema>;
type ReserveMetadata = z.infer<typeof activityTrackReserveMetadataSchema>;

export class ActivityTrackNotFoundError extends Error {
  readonly code = 'ACTIVITY_TRACK_NOT_FOUND';

  constructor() {
    super('ACTIVITY_TRACK_NOT_FOUND');
    this.name = 'ActivityTrackNotFoundError';
  }
}

export class ActivityTrackUploadStateError extends Error {
  constructor(
    readonly code:
      | 'UPLOAD_FAILED'
      | 'UPLOAD_NOT_PREPARED'
      | 'UPLOAD_NOT_STAGED'
      | 'UPLOAD_QUOTA_EXCEEDED'
      | 'UPLOAD_HISTORY_QUOTA_EXCEEDED'
      | 'TRACK_QUOTA_EXCEEDED'
      | 'TRACK_CLEANUP_BACKLOG_EXCEEDED'
      | 'TRACK_REVISION_LIMIT'
      | 'ACTIVITY_SOURCE_SUPPRESSED',
  ) {
    super(code);
    this.name = 'ActivityTrackUploadStateError';
  }
}

/** Object facts the API produces from bytes it stored itself, never from a client claim. */
export interface PreparedActivityTrackObjects {
  readonly raw: {
    readonly storageRef: string;
    readonly sizeBytes: number;
    readonly sha256: string;
    readonly format: 'fit' | 'gpx';
    readonly originalFileName: string | null;
  };
  readonly normalized: {
    readonly storageRef: string;
    readonly sizeBytes: number;
    readonly sha256: string;
  };
  readonly mapPath: {
    readonly storageRef: string;
    readonly sizeBytes: number;
    readonly sha256: string;
  };
  readonly parse: {
    readonly parserId: string;
    readonly parserVersion: 1;
    readonly recordedSourceKind: 'fit-session' | 'gpx-trk';
    readonly correspondenceDigest: string;
    readonly sampleCount: number;
    readonly positionedSampleCount: number;
    readonly segmentCount: number;
    readonly segmentPolicy: unknown;
    readonly distances: unknown;
  };
}

export interface ActivityTrackObjectRef {
  readonly storageRef: string;
  readonly activityId: string;
  readonly trackId: string;
  readonly artifactKind: 'raw' | 'normalized' | 'map_path';
  readonly mediaType: string;
  readonly byteSize: number;
  readonly sha256: string;
  readonly originalFileName: string | null;
  readonly trackRevision: number;
}

/**
 * Internal facts of a reservation. They never leave the server as a DTO: the public
 * reservation carries only ids and state, while the parse needs the source revision and
 * the track revision this upload reserved.
 */
export interface ActivityTrackUploadContext {
  readonly uploadId: string;
  readonly activityId: string;
  readonly trackId: string;
  readonly sourceKind: 'fit' | 'fixture' | 'manual';
  readonly sourceId: string;
  readonly sourceRevision: number;
  readonly trackRevision: number;
  readonly recordedTrackIndex: number;
  readonly state: 'reserved' | 'prepared' | 'staged' | 'finalized' | 'failed';
}

export interface ActivityTrackRepository {
  getUpload(athleteId: string, uploadId: string): Promise<Reservation>;
  getUploadContext(athleteId: string, uploadId: string): Promise<ActivityTrackUploadContext>;
  reserve(
    athleteId: string,
    activityId: string,
    metadata: ReserveMetadata,
    requestIdempotencyKey: string,
  ): Promise<Reservation>;
  prepareObjects(
    athleteId: string,
    uploadId: string,
    prepared: PreparedActivityTrackObjects,
  ): Promise<Reservation>;
  markStaged(athleteId: string, uploadId: string): Promise<Reservation>;
  /**
   * True while this upload may still publish: live, prepared or staged, and inside the
   * window preparation granted it. A writer checks this immediately before it makes any
   * object visible.
   */
  publicationFenceOpen(athleteId: string, uploadId: string): Promise<boolean>;
  /**
   * Reclaim the objects of an upload that was cancelled while its writer was publishing.
   * A still-live upload is left alone, so this can never delete a legitimate publication.
   */
  requeueObjects(athleteId: string, uploadId: string): Promise<{ requeued: number }>;
  finalize(athleteId: string, uploadId: string): Promise<ReadResult>;
  fail(athleteId: string, uploadId: string, code: string): Promise<{ failed: true }>;
  read(athleteId: string, activityId: string): Promise<ReadResult>;
  resolveObject(
    athleteId: string,
    activityId: string,
    variant: 'raw' | 'normalized' | 'map_path',
  ): Promise<ActivityTrackObjectRef | null>;
}

const instant = (value: unknown) =>
  value instanceof Date ? value.toISOString() : new Date(z.string().parse(value)).toISOString();

const intentRowSchema = z.object({
  upload_id: uuid,
  activity_id: uuid,
  track_id: uuid,
  source_kind: z.enum(['fit', 'fixture', 'manual']),
  source_id: z.string().min(1).max(200),
  source_revision: z.number().int().positive(),
  expected_activity_revision: z.number().int().positive(),
  recorded_track_index: z.number().int().nonnegative(),
  track_revision: z.number().int().positive(),
  idempotency_key: z.string(),
  request_digest: z.string(),
  raw_temporary_ref: z.string().min(1).max(512),
  normalized_temporary_ref: z.string().min(1).max(512),
  map_path_temporary_ref: z.string().min(1).max(512),
  raw_storage_ref: z.string().nullable(),
  normalized_storage_ref: z.string().nullable(),
  map_path_storage_ref: z.string().nullable(),
  format: z.enum(['fit', 'gpx']).nullable(),
  recorded_source_kind: z.enum(['fit-session', 'gpx-trk']).nullable(),
  parser_id: z.string().nullable(),
  parser_version: z.number().int().nullable(),
  correspondence_digest: z.string().nullable(),
  original_filename: z.string().nullable(),
  raw_size_bytes: z.coerce.number().int().nullable(),
  raw_content_hash: z.string().nullable(),
  normalized_size_bytes: z.coerce.number().int().nullable(),
  normalized_content_hash: z.string().nullable(),
  map_path_size_bytes: z.coerce.number().int().nullable(),
  map_path_content_hash: z.string().nullable(),
  sample_count: z.number().int().nullable(),
  positioned_sample_count: z.number().int().nullable(),
  segment_count: z.number().int().nullable(),
  segment_policy: z.unknown().nullable(),
  distances: z.unknown().nullable(),
  state: z.enum(['reserved', 'prepared', 'staged', 'finalized', 'failed']),
  failure_code: z.string().nullable(),
  created_at: z.union([z.date(), z.string()]),
  updated_at: z.union([z.date(), z.string()]),
  expires_at: z.union([z.date(), z.string()]),
});

function reservation(row: z.infer<typeof intentRowSchema>): Reservation {
  return activityTrackUploadReservationSchema.parse({
    uploadId: row.upload_id,
    activityId: row.activity_id,
    trackId: row.track_id,
    state: row.state,
    createdAt: instant(row.created_at),
    updatedAt: instant(row.updated_at),
  });
}

function digest(value: unknown) {
  return createHash('sha256').update(JSON.stringify(value)).digest('hex');
}

async function tenantLock(tx: Transaction) {
  await tx.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))', [tx.athleteId]);
}

async function databaseNow(tx: Transaction) {
  return instant((await tx.query('SELECT statement_timestamp() AS at')).rows[0]?.['at']);
}

async function expireUploads(tx: Transaction) {
  await tx.query('SELECT public.expire_activity_track_uploads(statement_timestamp())');
}

function temporaryRef(input: {
  tenantId: string;
  activityId: string;
  trackId: string;
  uploadId: string;
  artifactKind: 'raw' | 'normalized' | 'map_path';
}) {
  return `private/v1/tenants/${input.tenantId}/activities/${input.activityId}/tracks/${input.trackId}/temporary/${input.uploadId}/${input.artifactKind}`;
}

function assertFinalRef(input: {
  storageRef: string;
  tenantId: string;
  activityId: string;
  trackId: string;
  uploadId: string;
  artifactKind: 'raw' | 'normalized' | 'map_path';
  sha256: string;
  extension: string;
}) {
  const match = FINAL_REF_PATTERN.exec(input.storageRef);
  if (
    match?.[1] !== input.tenantId ||
    match[2] !== input.activityId ||
    match[3] !== input.trackId ||
    match[4] !== input.artifactKind ||
    match[5] !== input.uploadId ||
    match[6] !== input.sha256 ||
    match[7] !== input.extension
  )
    throw new PersistenceConflict('IDEMPOTENCY_CONFLICT');
}

/** Add references to the watch index. Recording the same reference twice is harmless. */
async function recordObjectRefs(tx: Transaction, refs: readonly string[], at: string) {
  await tx.query(
    `INSERT INTO activity_track_object_ref(storage_ref,athlete_id,recorded_at)
     SELECT unnest($2::text[]),$1,$3 ON CONFLICT(storage_ref) DO NOTHING`,
    [tx.athleteId, refs, at],
  );
}

async function assertUploadQuota(tx: Transaction) {
  await tx.query('SELECT public.compact_activity_track_upload_history(100)');
  const quota = await tx.query(
    `SELECT
       count(*) FILTER (WHERE state IN ('reserved','prepared','staged'))::integer AS pending_count,
       count(*) FILTER (WHERE state='failed')::integer AS failed_count,
       coalesce(sum(coalesce(raw_size_bytes,0)+coalesce(normalized_size_bytes,0)
         +coalesce(map_path_size_bytes,0)) FILTER (WHERE state IN ('prepared','staged')),0)::bigint
         AS pending_bytes
     FROM activity_track_upload_intent WHERE athlete_id=$1`,
    [tx.athleteId],
  );
  const pendingCount = z.number().int().parse(quota.rows[0]?.['pending_count']);
  const failedCount = z.number().int().parse(quota.rows[0]?.['failed_count']);
  const pendingBytes = z.coerce.number().int().parse(quota.rows[0]?.['pending_bytes']);
  if (pendingCount >= MAX_ACTIVE_TRACK_UPLOADS || pendingBytes > MAX_PENDING_TRACK_UPLOAD_BYTES)
    throw new ActivityTrackUploadStateError('UPLOAD_QUOTA_EXCEEDED');
  if (failedCount + pendingCount >= MAX_TRACK_UPLOAD_HISTORY)
    throw new ActivityTrackUploadStateError('UPLOAD_HISTORY_QUOTA_EXCEEDED');
}

/**
 * Bytes already scheduled for reclamation but not yet gone.
 *
 * Deleting an activity does not delete its objects: it schedules them, in the same
 * transaction as the tombstone, for the durable manifest to reclaim. Until the worker gets
 * there the bytes are still on the object store, so they are bounded separately from live
 * data — otherwise store-then-delete in a loop passes the live quota forever while the
 * backlog grows.
 */
async function assertCleanupBacklog(tx: Transaction) {
  const pending = await tx.query('SELECT public.activity_track_pending_cleanup_bytes() AS bytes');
  if (z.coerce.number().int().parse(pending.rows[0]?.['bytes']) > MAX_PENDING_CLEANUP_TRACK_BYTES)
    throw new ActivityTrackUploadStateError('TRACK_CLEANUP_BACKLOG_EXCEEDED');
}

/**
 * Tenant byte quota for live data, counted after the revision is written.
 *
 * What is kept and what is billed are two different things. Revision metadata of a deleted
 * activity is history and stays; its objects are scheduled for reclamation with the
 * tombstone. Billing therefore counts only revisions of a live activity — otherwise a
 * tenant at the cap could delete everything and still be refused, because the rows it is
 * charged for never go away — while {@link assertCleanupBacklog} bounds what deletion has
 * scheduled but not yet freed.
 */
async function assertStoredTrackQuota(tx: Transaction) {
  const total = await tx.query(
    `SELECT coalesce(sum(r.raw_size_bytes+r.normalized_size_bytes+r.map_path_size_bytes),0)::bigint
       AS bytes
     FROM activity_track_revision r JOIN activity_canonical c
       ON c.athlete_id=r.athlete_id AND c.id=r.activity_id
     WHERE r.athlete_id=$1 AND NOT c.deleted`,
    [tx.athleteId],
  );
  if (z.coerce.number().int().parse(total.rows[0]?.['bytes']) > MAX_LIVE_TRACK_BYTES)
    throw new ActivityTrackUploadStateError('TRACK_QUOTA_EXCEEDED');
}

const REVISION_COLUMNS = `r.activity_id,r.track_id,r.track_revision,r.source_kind,r.source_id,
  r.source_revision,r.recorded_source_kind,r.parser_id,r.parser_version,r.correspondence_digest,
  r.format,r.original_filename,r.raw_size_bytes,r.raw_content_hash,r.normalized_size_bytes,
  r.normalized_content_hash,r.map_path_size_bytes,r.map_path_content_hash,r.sample_count,
  r.positioned_sample_count,r.segment_count,r.segment_policy,r.distances,r.created_at`;

function toRevision(row: Record<string, unknown>) {
  const parsed = z
    .object({
      activity_id: uuid,
      track_id: uuid,
      track_revision: z.number().int().positive(),
      source_kind: z.enum(['fit', 'fixture', 'manual']),
      source_id: z.string(),
      source_revision: z.number().int().positive(),
      recorded_source_kind: z.enum(['fit-session', 'gpx-trk']),
      parser_id: z.string(),
      parser_version: z.literal(1),
      correspondence_digest: sha256,
      format: z.enum(['fit', 'gpx']),
      original_filename: z.string().nullable(),
      raw_size_bytes: z.coerce.number().int(),
      raw_content_hash: sha256,
      normalized_size_bytes: z.coerce.number().int(),
      normalized_content_hash: sha256,
      map_path_size_bytes: z.coerce.number().int(),
      map_path_content_hash: sha256,
      sample_count: z.number().int(),
      positioned_sample_count: z.number().int(),
      segment_count: z.number().int(),
      segment_policy: z.unknown(),
      distances: z.unknown(),
      created_at: z.union([z.date(), z.string()]),
    })
    .parse(row);
  return activityTrackRevisionSchema.parse({
    trackId: parsed.track_id,
    activityId: parsed.activity_id,
    sourceKind: parsed.source_kind,
    sourceId: parsed.source_id,
    sourceRevision: parsed.source_revision,
    trackRevision: parsed.track_revision,
    recordedSourceKind: parsed.recorded_source_kind,
    correspondence: {
      algorithm: 'track-correspondence-v1',
      parserId: parsed.parser_id,
      parserVersion: 1,
      digest: parsed.correspondence_digest,
    },
    file: {
      originalFileName: parsed.original_filename,
      format: parsed.format,
      byteSize: parsed.raw_size_bytes,
      sha256: parsed.raw_content_hash,
    },
    derivatives: [
      {
        kind: 'normalized',
        byteSize: parsed.normalized_size_bytes,
        sha256: parsed.normalized_content_hash,
      },
      {
        kind: 'map_path',
        byteSize: parsed.map_path_size_bytes,
        sha256: parsed.map_path_content_hash,
      },
    ],
    sampleCount: parsed.sample_count,
    positionedSampleCount: parsed.positioned_sample_count,
    segmentCount: parsed.segment_count,
    segmentPolicy: trackSegmentPolicySchema.parse(parsed.segment_policy),
    distances: trackDistancesSchema.parse(parsed.distances),
    createdAt: instant(parsed.created_at),
  });
}

/** The current revision of a live activity. A deleted activity never resolves to a track. */
async function readTrack(tx: Transaction, activityId: string): Promise<ReadResult> {
  const found = await tx.query(
    `SELECT ${REVISION_COLUMNS} FROM activity_track t
     JOIN activity_track_revision r ON r.athlete_id=t.athlete_id AND r.activity_id=t.activity_id
       AND r.track_revision=t.track_revision
     JOIN activity_canonical c ON c.athlete_id=t.athlete_id AND c.id=t.activity_id
     WHERE t.athlete_id=$1 AND t.activity_id=$2 AND NOT c.deleted`,
    [tx.athleteId, activityId],
  );
  if (!found.rows[0])
    return activityTrackReadResultSchema.parse({ status: 'unavailable', activityId });
  return activityTrackReadResultSchema.parse({
    status: 'available',
    track: toRevision(found.rows[0]),
  });
}

async function finishCommand(
  tx: Transaction,
  key: string,
  request: unknown,
  receipt: unknown,
  event: { activityId: string; trackRevision: number },
  topic: string,
) {
  await enqueue(tx, { id: randomUUID(), idempotencyKey: key, topic, payload: event });
  await tx.query(
    'INSERT INTO command_receipt(athlete_id,idempotency_key,request,result) VALUES($1,$2,$3::jsonb,$4::jsonb)',
    [
      tx.athleteId,
      key,
      JSON.stringify({ sha256: digest(request) }),
      JSON.stringify(receipt ?? null),
    ],
  );
}

export function createActivityTrackRepository(database: Database): ActivityTrackRepository {
  return {
    getUpload(athleteId, rawUploadId) {
      const tenantId = uuid.parse(athleteId);
      const uploadId = uuid.parse(rawUploadId);
      return database.tenant(tenantId, async (tx) => {
        await expireUploads(tx);
        const found = await tx.query(
          'SELECT * FROM activity_track_upload_intent WHERE athlete_id=$1 AND upload_id=$2',
          [tenantId, uploadId],
        );
        if (!found.rows[0]) throw new ActivityTrackNotFoundError();
        return reservation(intentRowSchema.parse(found.rows[0]));
      });
    },

    getUploadContext(athleteId, rawUploadId) {
      const tenantId = uuid.parse(athleteId);
      const uploadId = uuid.parse(rawUploadId);
      return database.tenant(tenantId, async (tx) => {
        await expireUploads(tx);
        const found = await tx.query(
          'SELECT * FROM activity_track_upload_intent WHERE athlete_id=$1 AND upload_id=$2',
          [tenantId, uploadId],
        );
        if (!found.rows[0]) throw new ActivityTrackNotFoundError();
        const row = intentRowSchema.parse(found.rows[0]);
        return {
          uploadId: row.upload_id,
          activityId: row.activity_id,
          trackId: row.track_id,
          sourceKind: row.source_kind,
          sourceId: row.source_id,
          sourceRevision: row.source_revision,
          trackRevision: row.track_revision,
          recordedTrackIndex: row.recorded_track_index,
          state: row.state,
        };
      });
    },

    reserve(athleteId, rawActivityId, rawMetadata, rawKey) {
      const tenantId = uuid.parse(athleteId);
      const activityId = uuid.parse(rawActivityId);
      const metadata = activityTrackReserveMetadataSchema.parse(rawMetadata);
      const key = idempotencyKey.parse(rawKey);
      return database.tenant(tenantId, async (tx) => {
        await tenantLock(tx);
        await expireUploads(tx);
        const request = { activityId, metadata };
        const requestDigest = digest(request);
        const prior = await tx.query(
          'SELECT * FROM activity_track_upload_intent WHERE athlete_id=$1 AND idempotency_key=$2',
          [tenantId, key],
        );
        if (prior.rows[0]) {
          const parsed = intentRowSchema.parse(prior.rows[0]);
          if (parsed.request_digest !== requestDigest)
            throw new PersistenceConflict('IDEMPOTENCY_CONFLICT');
          return reservation(parsed);
        }
        await assertUploadQuota(tx);
        await assertCleanupBacklog(tx);
        // Ownership and the source come from the stored activity, never from the request.
        const activity = await tx.query(
          `SELECT c.revision,c.deleted,s.kind,s.source_id,s.source_revision,
             EXISTS(SELECT 1 FROM activity_suppression d WHERE d.athlete_id=s.athlete_id
               AND d.kind=s.kind AND d.source_id=s.source_id) AS suppressed
           FROM activity_canonical c
           JOIN activity_source_head s ON s.athlete_id=c.athlete_id AND s.activity_id=c.id
           WHERE c.athlete_id=$1 AND c.id=$2`,
          [tenantId, activityId],
        );
        const row = activity.rows[0];
        if (!row || row['deleted'] === true) throw new ActivityTrackNotFoundError();
        if (row['suppressed'] === true)
          throw new ActivityTrackUploadStateError('ACTIVITY_SOURCE_SUPPRESSED');
        if (z.number().int().parse(row['revision']) !== metadata.expectedActivityRevision)
          throw new PersistenceConflict('REVISION_CONFLICT');
        const head = await tx.query(
          'SELECT track_id,track_revision FROM activity_track WHERE athlete_id=$1 AND activity_id=$2',
          [tenantId, activityId],
        );
        const currentRevision = head.rows[0]
          ? z.number().int().parse(head.rows[0]['track_revision'])
          : 0;
        if (currentRevision >= MAX_TRACK_REVISIONS_PER_ACTIVITY)
          throw new ActivityTrackUploadStateError('TRACK_REVISION_LIMIT');
        const trackId = head.rows[0] ? uuid.parse(head.rows[0]['track_id']) : randomUUID();
        const uploadId = randomUUID();
        const at = await databaseNow(tx);
        const expiresAt = new Date(
          new Date(at).getTime() + UPLOAD_EXPIRY_MINUTES * 60_000,
        ).toISOString();
        const refs = (['raw', 'normalized', 'map_path'] as const).map((artifactKind) =>
          temporaryRef({ tenantId, activityId, trackId, uploadId, artifactKind }),
        );
        // Every reference enters the watch index before its object can exist, and stays there
        // after the upload row is gone: the reconciliation sweep reads this index, not the
        // upload ledger.
        await recordObjectRefs(tx, refs, at);
        const inserted = await tx.query(
          `INSERT INTO activity_track_upload_intent
           (athlete_id,upload_id,idempotency_key,request_digest,activity_id,track_id,source_kind,
            source_id,source_revision,expected_activity_revision,recorded_track_index,track_revision,
            raw_temporary_ref,normalized_temporary_ref,map_path_temporary_ref,state,
            created_at,updated_at,expires_at)
           VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,'reserved',$16,$16,$17)
           RETURNING *`,
          [
            tenantId,
            uploadId,
            key,
            requestDigest,
            activityId,
            trackId,
            row['kind'],
            row['source_id'],
            row['source_revision'],
            metadata.expectedActivityRevision,
            metadata.recordedTrackIndex,
            currentRevision + 1,
            refs[0],
            refs[1],
            refs[2],
            at,
            expiresAt,
          ],
        );
        return reservation(intentRowSchema.parse(inserted.rows[0]));
      });
    },

    prepareObjects(athleteId, rawUploadId, rawPrepared) {
      const tenantId = uuid.parse(athleteId);
      const uploadId = uuid.parse(rawUploadId);
      const prepared = z
        .strictObject({
          raw: z.strictObject({
            storageRef: finalStorageRef,
            sizeBytes: z.number().int().min(1).max(33_554_432),
            sha256,
            format: z.enum(['fit', 'gpx']),
            originalFileName: z.string().min(1).max(1024).nullable(),
          }),
          normalized: z.strictObject({
            storageRef: finalStorageRef,
            sizeBytes: z.number().int().min(1).max(8_388_608),
            sha256,
          }),
          mapPath: z.strictObject({
            storageRef: finalStorageRef,
            sizeBytes: z.number().int().min(1).max(8_388_608),
            sha256,
          }),
          parse: z.strictObject({
            parserId: z.enum(['fit-track-v1', 'gpx-track-v1', 'fit-python-export-v1']),
            parserVersion: z.literal(1),
            recordedSourceKind: z.enum(['fit-session', 'gpx-trk']),
            correspondenceDigest: sha256,
            sampleCount: z.number().int().min(1).max(200_000),
            positionedSampleCount: z.number().int().min(0).max(200_000),
            segmentCount: z.number().int().min(1).max(2_000),
            segmentPolicy: trackSegmentPolicySchema,
            distances: trackDistancesSchema,
          }),
        })
        .parse(rawPrepared);
      return database.tenant(tenantId, async (tx) => {
        await tenantLock(tx);
        await expireUploads(tx);
        const found = await tx.query(
          'SELECT * FROM activity_track_upload_intent WHERE athlete_id=$1 AND upload_id=$2 FOR UPDATE',
          [tenantId, uploadId],
        );
        if (!found.rows[0]) throw new ActivityTrackNotFoundError();
        const prior = intentRowSchema.parse(found.rows[0]);
        const expected = {
          tenantId,
          activityId: prior.activity_id,
          trackId: prior.track_id,
          uploadId,
        };
        assertFinalRef({
          ...expected,
          storageRef: prepared.raw.storageRef,
          artifactKind: 'raw',
          sha256: prepared.raw.sha256,
          extension: prepared.raw.format,
        });
        assertFinalRef({
          ...expected,
          storageRef: prepared.normalized.storageRef,
          artifactKind: 'normalized',
          sha256: prepared.normalized.sha256,
          extension: 'json',
        });
        assertFinalRef({
          ...expected,
          storageRef: prepared.mapPath.storageRef,
          artifactKind: 'map_path',
          sha256: prepared.mapPath.sha256,
          extension: 'json',
        });
        if (prepared.parse.positionedSampleCount > prepared.parse.sampleCount)
          throw new PersistenceConflict('IDEMPOTENCY_CONFLICT');
        if (prior.state === 'failed') throw new ActivityTrackUploadStateError('UPLOAD_FAILED');
        if (prior.state !== 'reserved') {
          // A retry of the same upload must present exactly the same facts.
          if (
            prior.raw_storage_ref !== prepared.raw.storageRef ||
            prior.normalized_storage_ref !== prepared.normalized.storageRef ||
            prior.map_path_storage_ref !== prepared.mapPath.storageRef ||
            prior.correspondence_digest !== prepared.parse.correspondenceDigest ||
            prior.raw_content_hash !== prepared.raw.sha256
          )
            throw new PersistenceConflict('IDEMPOTENCY_CONFLICT');
          return reservation(prior);
        }
        const at = await databaseNow(tx);
        const changed = await tx.query(
          `UPDATE activity_track_upload_intent SET
             raw_storage_ref=$3,normalized_storage_ref=$4,map_path_storage_ref=$5,format=$6,
             recorded_source_kind=$7,parser_id=$8,parser_version=1,correspondence_digest=$9,
             original_filename=$10,raw_size_bytes=$11,raw_content_hash=$12,
             normalized_size_bytes=$13,normalized_content_hash=$14,map_path_size_bytes=$15,
             map_path_content_hash=$16,sample_count=$17,positioned_sample_count=$18,
             segment_count=$19,segment_policy=$20::jsonb,distances=$21::jsonb,
             state='prepared',prepared_at=$22,updated_at=$22,
             publication_lease_until=$22::timestamptz+make_interval(secs=>$23::double precision)
           WHERE athlete_id=$1 AND upload_id=$2 RETURNING *`,
          [
            tenantId,
            uploadId,
            prepared.raw.storageRef,
            prepared.normalized.storageRef,
            prepared.mapPath.storageRef,
            prepared.raw.format,
            prepared.parse.recordedSourceKind,
            prepared.parse.parserId,
            prepared.parse.correspondenceDigest,
            prepared.raw.originalFileName,
            prepared.raw.sizeBytes,
            prepared.raw.sha256,
            prepared.normalized.sizeBytes,
            prepared.normalized.sha256,
            prepared.mapPath.sizeBytes,
            prepared.mapPath.sha256,
            prepared.parse.sampleCount,
            prepared.parse.positionedSampleCount,
            prepared.parse.segmentCount,
            JSON.stringify(prepared.parse.segmentPolicy),
            JSON.stringify(prepared.parse.distances),
            at,
            PUBLICATION_FENCE_SECONDS,
          ],
        );
        await recordObjectRefs(
          tx,
          [prepared.raw.storageRef, prepared.normalized.storageRef, prepared.mapPath.storageRef],
          at,
        );
        await tx.query('SELECT public.protect_activity_track_upload_objects($1)', [uploadId]);
        const quota = await tx.query(
          `SELECT coalesce(sum(raw_size_bytes+normalized_size_bytes+map_path_size_bytes),0)::bigint
             AS pending_bytes FROM activity_track_upload_intent
           WHERE athlete_id=$1 AND state IN ('prepared','staged')`,
          [tenantId],
        );
        if (
          z.coerce.number().int().parse(quota.rows[0]?.['pending_bytes']) >
          MAX_PENDING_TRACK_UPLOAD_BYTES
        )
          throw new ActivityTrackUploadStateError('UPLOAD_QUOTA_EXCEEDED');
        return reservation(intentRowSchema.parse(changed.rows[0]));
      });
    },

    publicationFenceOpen(athleteId, rawUploadId) {
      const tenantId = uuid.parse(athleteId);
      const uploadId = uuid.parse(rawUploadId);
      return database.tenant(tenantId, async (tx) => {
        const result = await tx.query(
          'SELECT public.activity_track_publication_fence_open($1) AS open',
          [uploadId],
        );
        return result.rows[0]?.['open'] === true;
      });
    },

    requeueObjects(athleteId, rawUploadId) {
      const tenantId = uuid.parse(athleteId);
      const uploadId = uuid.parse(rawUploadId);
      return database.tenant(tenantId, async (tx) => {
        const result = await tx.query(
          'SELECT public.requeue_activity_track_upload_refs($1) AS requeued',
          [uploadId],
        );
        return { requeued: z.coerce.number().int().parse(result.rows[0]?.['requeued']) };
      });
    },

    markStaged(athleteId, rawUploadId) {
      const tenantId = uuid.parse(athleteId);
      const uploadId = uuid.parse(rawUploadId);
      return database.tenant(tenantId, async (tx) => {
        await tenantLock(tx);
        await expireUploads(tx);
        const found = await tx.query(
          'SELECT * FROM activity_track_upload_intent WHERE athlete_id=$1 AND upload_id=$2 FOR UPDATE',
          [tenantId, uploadId],
        );
        if (!found.rows[0]) throw new ActivityTrackNotFoundError();
        const prior = intentRowSchema.parse(found.rows[0]);
        if (prior.state === 'failed') throw new ActivityTrackUploadStateError('UPLOAD_FAILED');
        if (prior.state === 'reserved')
          throw new ActivityTrackUploadStateError('UPLOAD_NOT_PREPARED');
        if (prior.state !== 'prepared') return reservation(prior);
        await tx.query('SELECT public.protect_activity_track_upload_objects($1)', [uploadId]);
        const at = await databaseNow(tx);
        const changed = await tx.query(
          `UPDATE activity_track_upload_intent SET state='staged',staged_at=$3,updated_at=$3
           WHERE athlete_id=$1 AND upload_id=$2 RETURNING *`,
          [tenantId, uploadId, at],
        );
        return reservation(intentRowSchema.parse(changed.rows[0]));
      });
    },

    finalize(athleteId, rawUploadId) {
      const tenantId = uuid.parse(athleteId);
      const uploadId = uuid.parse(rawUploadId);
      return database.tenant(tenantId, async (tx) => {
        await tenantLock(tx);
        const found = await tx.query(
          'SELECT * FROM activity_track_upload_intent WHERE athlete_id=$1 AND upload_id=$2 FOR UPDATE',
          [tenantId, uploadId],
        );
        if (!found.rows[0]) throw new ActivityTrackNotFoundError();
        const intent = intentRowSchema.parse(found.rows[0]);
        if (intent.state === 'failed') throw new ActivityTrackUploadStateError('UPLOAD_FAILED');
        if (intent.state === 'reserved' || intent.state === 'prepared')
          throw new ActivityTrackUploadStateError('UPLOAD_NOT_STAGED');
        if (intent.state === 'finalized') return readTrack(tx, intent.activity_id);
        if (
          intent.raw_storage_ref === null ||
          intent.normalized_storage_ref === null ||
          intent.map_path_storage_ref === null ||
          intent.format === null ||
          intent.recorded_source_kind === null ||
          intent.parser_id === null ||
          intent.correspondence_digest === null ||
          intent.raw_size_bytes === null ||
          intent.raw_content_hash === null ||
          intent.normalized_size_bytes === null ||
          intent.normalized_content_hash === null ||
          intent.map_path_size_bytes === null ||
          intent.map_path_content_hash === null ||
          intent.sample_count === null ||
          intent.positioned_sample_count === null ||
          intent.segment_count === null
        )
          throw new Error('INVALID_STAGED_ACTIVITY_TRACK_UPLOAD');
        await tx.query('SELECT public.protect_activity_track_upload_objects($1)', [uploadId]);
        // Deletion suppression is re-checked here, inside the finalize transaction: an
        // activity deleted while the bytes were in flight must not gain a track.
        const activity = await tx.query(
          `SELECT c.revision,c.deleted,
             EXISTS(SELECT 1 FROM activity_suppression d WHERE d.athlete_id=c.athlete_id
               AND d.kind=$3 AND d.source_id=$4) AS suppressed
           FROM activity_canonical c WHERE c.athlete_id=$1 AND c.id=$2 FOR UPDATE`,
          [tenantId, intent.activity_id, intent.source_kind, intent.source_id],
        );
        const activityRow = activity.rows[0];
        if (!activityRow || activityRow['deleted'] === true) throw new ActivityTrackNotFoundError();
        if (activityRow['suppressed'] === true)
          throw new ActivityTrackUploadStateError('ACTIVITY_SOURCE_SUPPRESSED');
        if (z.number().int().parse(activityRow['revision']) !== intent.expected_activity_revision)
          throw new PersistenceConflict('REVISION_CONFLICT');
        const head = (
          await tx.query(
            'SELECT track_id,track_revision FROM activity_track WHERE athlete_id=$1 AND activity_id=$2 FOR UPDATE',
            [tenantId, intent.activity_id],
          )
        ).rows[0];
        const currentRevision = head ? z.number().int().parse(head['track_revision']) : 0;
        if (currentRevision + 1 !== intent.track_revision)
          throw new PersistenceConflict('REVISION_CONFLICT');
        const at = await databaseNow(tx);
        if (head) {
          // A re-upload of a recording the head already holds is a duplicate, not a new
          // revision: the correspondence and the original bytes are both unchanged.
          const current = (
            await tx.query(
              `SELECT correspondence_digest,raw_content_hash FROM activity_track_revision
               WHERE athlete_id=$1 AND activity_id=$2 AND track_revision=$3`,
              [tenantId, intent.activity_id, currentRevision],
            )
          ).rows[0];
          if (
            current?.['correspondence_digest'] === intent.correspondence_digest &&
            current['raw_content_hash'] === intent.raw_content_hash
          ) {
            await tx.query('SELECT public.supersede_activity_track_upload_objects($1)', [uploadId]);
            await tx.query(
              `UPDATE activity_track_upload_intent SET state='finalized',finalized_at=$3,updated_at=$3
               WHERE athlete_id=$1 AND upload_id=$2`,
              [tenantId, uploadId, at],
            );
            return readTrack(tx, intent.activity_id);
          }
        }
        const revisionId = randomUUID();
        for (const object of [
          {
            ref: intent.raw_storage_ref,
            kind: 'raw',
            hash: intent.raw_content_hash,
            size: intent.raw_size_bytes,
            mediaType: intent.format === 'gpx' ? 'application/gpx+xml' : 'application/octet-stream',
          },
          {
            ref: intent.normalized_storage_ref,
            kind: 'normalized',
            hash: intent.normalized_content_hash,
            size: intent.normalized_size_bytes,
            mediaType: 'application/json',
          },
          {
            ref: intent.map_path_storage_ref,
            kind: 'map_path',
            hash: intent.map_path_content_hash,
            size: intent.map_path_size_bytes,
            mediaType: 'application/json',
          },
        ]) {
          await tx.query(
            `INSERT INTO activity_track_object
             (athlete_id,storage_ref,artifact_kind,content_hash,size_bytes,media_type,created_at)
             VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(athlete_id,storage_ref) DO NOTHING`,
            [tenantId, object.ref, object.kind, object.hash, object.size, object.mediaType, at],
          );
          const stored = await tx.query(
            `SELECT content_hash,size_bytes,artifact_kind FROM activity_track_object
             WHERE athlete_id=$1 AND storage_ref=$2`,
            [tenantId, object.ref],
          );
          if (
            stored.rows[0]?.['content_hash'] !== object.hash ||
            Number(stored.rows[0]?.['size_bytes']) !== object.size ||
            stored.rows[0]?.['artifact_kind'] !== object.kind
          )
            throw new PersistenceConflict('IDEMPOTENCY_CONFLICT');
        }
        if (head) {
          await tx.query(
            `UPDATE activity_track SET track_revision=$3,revision_id=$4,updated_at=$5
             WHERE athlete_id=$1 AND activity_id=$2`,
            [tenantId, intent.activity_id, intent.track_revision, revisionId, at],
          );
        } else {
          await tx.query(
            `INSERT INTO activity_track
             (athlete_id,activity_id,track_id,source_kind,source_id,track_revision,revision_id,
              created_at,updated_at)
             VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8)`,
            [
              tenantId,
              intent.activity_id,
              intent.track_id,
              intent.source_kind,
              intent.source_id,
              intent.track_revision,
              revisionId,
              at,
            ],
          );
        }
        await tx.query(
          `INSERT INTO activity_track_revision
           (athlete_id,activity_id,track_id,track_revision,revision_id,upload_id,source_kind,
            source_id,source_revision,recorded_source_kind,parser_id,parser_version,
            correspondence_digest,format,original_filename,raw_storage_ref,raw_size_bytes,
            raw_content_hash,normalized_storage_ref,normalized_size_bytes,normalized_content_hash,
            map_path_storage_ref,map_path_size_bytes,map_path_content_hash,sample_count,
            positioned_sample_count,segment_count,segment_policy,distances,created_at)
           VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,1,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,
            $22,$23,$24,$25,$26,$27::jsonb,$28::jsonb,$29)`,
          [
            tenantId,
            intent.activity_id,
            intent.track_id,
            intent.track_revision,
            revisionId,
            uploadId,
            intent.source_kind,
            intent.source_id,
            intent.source_revision,
            intent.recorded_source_kind,
            intent.parser_id,
            intent.correspondence_digest,
            intent.format,
            intent.original_filename,
            intent.raw_storage_ref,
            intent.raw_size_bytes,
            intent.raw_content_hash,
            intent.normalized_storage_ref,
            intent.normalized_size_bytes,
            intent.normalized_content_hash,
            intent.map_path_storage_ref,
            intent.map_path_size_bytes,
            intent.map_path_content_hash,
            intent.sample_count,
            intent.positioned_sample_count,
            intent.segment_count,
            JSON.stringify(intent.segment_policy),
            JSON.stringify(intent.distances),
            at,
          ],
        );
        await assertStoredTrackQuota(tx);
        await assertCleanupBacklog(tx);
        const result = await readTrack(tx, intent.activity_id);
        if (result.status !== 'available') throw new ActivityTrackNotFoundError();
        await finishCommand(
          tx,
          `activity-track:store:${intent.idempotency_key}`,
          { kind: 'activity_track_store', uploadId },
          { status: 'available', activityId: intent.activity_id, revisionId },
          { activityId: intent.activity_id, trackRevision: intent.track_revision },
          'activity.track_stored',
        );
        await tx.query(
          `UPDATE activity_track_upload_intent SET state='finalized',finalized_at=$3,updated_at=$3
           WHERE athlete_id=$1 AND upload_id=$2`,
          [tenantId, uploadId, at],
        );
        return result;
      });
    },

    fail(athleteId, rawUploadId, rawCode) {
      const tenantId = uuid.parse(athleteId);
      const uploadId = uuid.parse(rawUploadId);
      const code = failureCode.parse(rawCode);
      return database.tenant(tenantId, async (tx) => {
        const result = await tx.query('SELECT public.fail_activity_track_upload($1,$2) AS failed', [
          uploadId,
          code,
        ]);
        if (result.rows[0]?.['failed'] !== true) throw new ActivityTrackNotFoundError();
        return { failed: true };
      });
    },

    read(athleteId, rawActivityId) {
      const tenantId = uuid.parse(athleteId);
      const activityId = uuid.parse(rawActivityId);
      return database.tenant(tenantId, (tx) => readTrack(tx, activityId));
    },

    resolveObject(athleteId, rawActivityId, rawVariant) {
      const tenantId = uuid.parse(athleteId);
      const activityId = uuid.parse(rawActivityId);
      const variant = z.enum(['raw', 'normalized', 'map_path']).parse(rawVariant);
      const column =
        variant === 'raw' ? 'raw' : variant === 'normalized' ? 'normalized' : 'map_path';
      return database.tenant(tenantId, async (tx) => {
        const found = await tx.query(
          `SELECT r.${column}_storage_ref AS storage_ref,r.${column}_size_bytes AS size_bytes,
             r.${column}_content_hash AS content_hash,r.track_id,r.track_revision,
             r.original_filename,r.format,o.media_type
           FROM activity_track t
           JOIN activity_track_revision r ON r.athlete_id=t.athlete_id AND r.activity_id=t.activity_id
             AND r.track_revision=t.track_revision
           JOIN activity_canonical c ON c.athlete_id=t.athlete_id AND c.id=t.activity_id
           JOIN activity_track_object o ON o.athlete_id=r.athlete_id
             AND o.storage_ref=r.${column}_storage_ref
           WHERE t.athlete_id=$1 AND t.activity_id=$2 AND NOT c.deleted`,
          [tenantId, activityId],
        );
        if (!found.rows[0]) return null;
        const row = z
          .object({
            storage_ref: finalStorageRef,
            size_bytes: z.coerce.number().int(),
            content_hash: sha256,
            track_id: uuid,
            track_revision: z.number().int().positive(),
            original_filename: z.string().nullable(),
            format: z.enum(['fit', 'gpx']),
            media_type: z.string().min(1).max(100),
          })
          .parse(found.rows[0]);
        return {
          storageRef: row.storage_ref,
          activityId,
          trackId: row.track_id,
          artifactKind: variant,
          mediaType: row.media_type,
          byteSize: row.size_bytes,
          sha256: row.content_hash,
          originalFileName: row.original_filename,
          trackRevision: row.track_revision,
        };
      });
    },
  };
}
