/* Generated by scripts/generate-responsive.mjs. Do not edit directly. */

export const responsiveSpec = {
  schemaVersion: 1,
  documentVersion: '0.2.2',
  status: 'specification_not_applied',
  widthBasis: 'layout_viewport_css_px',
  modes: [
    { id: 'mobile', minInclusive: 0, maxExclusive: 768, columns: 4, pagePaddingPx: 16, gapPx: 12 },
    {
      id: 'tablet',
      minInclusive: 768,
      maxExclusive: 1280,
      columns: 8,
      pagePaddingPx: 24,
      gapPx: 16,
    },
    {
      id: 'desktop',
      minInclusive: 1280,
      maxExclusive: null,
      columns: 12,
      pagePaddingPx: 32,
      gapPx: 24,
    },
  ],
  componentContainers: { standardMinPx: 560, workspaceMinPx: 960 },
  workspaceMaxWidthPx: 1600,
  reflowTestMinWidthPx: 320,
  testWidthsCssPx: [320, 360, 390, 600, 767, 768, 820, 1024, 1180, 1279, 1280, 1440, 1536, 1920],
  interaction: {
    primaryTargetProductGoalPx: 44,
    quickLogTargetHeightGoalPx: 48,
    detectPointerIndependently: true,
  },
  constraints: [
    'preserve_module_state_on_layout_change',
    'no_UA_based_mode',
    'no_offline_plan_approval',
    'no_hidden_critical_information',
  ],
} as const;
export const viewportFixtures = [
  { width: 320, height: 900 },
  { width: 360, height: 900 },
  { width: 390, height: 900 },
  { width: 600, height: 900 },
  { width: 767, height: 900 },
  { width: 768, height: 900 },
  { width: 820, height: 900 },
  { width: 1024, height: 900 },
  { width: 1180, height: 900 },
  { width: 1279, height: 900 },
  { width: 1280, height: 900 },
  { width: 1440, height: 900 },
  { width: 1536, height: 900 },
  { width: 1920, height: 900 },
] as const;
export const fractionalBoundaryWidths = [767.9, 768, 1279.9, 1280] as const;
export const storybookViewports = {
  width320: { name: '320px', styles: { width: '320px', height: '900px' }, type: 'mobile' },
  width360: { name: '360px', styles: { width: '360px', height: '900px' }, type: 'mobile' },
  width390: { name: '390px', styles: { width: '390px', height: '900px' }, type: 'mobile' },
  width600: { name: '600px', styles: { width: '600px', height: '900px' }, type: 'mobile' },
  width767: { name: '767px', styles: { width: '767px', height: '900px' }, type: 'mobile' },
  width768: { name: '768px', styles: { width: '768px', height: '900px' }, type: 'tablet' },
  width820: { name: '820px', styles: { width: '820px', height: '900px' }, type: 'tablet' },
  width1024: { name: '1024px', styles: { width: '1024px', height: '900px' }, type: 'tablet' },
  width1180: { name: '1180px', styles: { width: '1180px', height: '900px' }, type: 'tablet' },
  width1279: { name: '1279px', styles: { width: '1279px', height: '900px' }, type: 'tablet' },
  width1280: { name: '1280px', styles: { width: '1280px', height: '900px' }, type: 'desktop' },
  width1440: { name: '1440px', styles: { width: '1440px', height: '900px' }, type: 'desktop' },
  width1536: { name: '1536px', styles: { width: '1536px', height: '900px' }, type: 'desktop' },
  width1920: { name: '1920px', styles: { width: '1920px', height: '900px' }, type: 'desktop' },
} as const;
export type LayoutMode = (typeof responsiveSpec.modes)[number]['id'];
export function getLayoutMode(width: number): LayoutMode {
  if (!Number.isFinite(width) || width < 0)
    throw new RangeError('Width must be a finite non-negative CSS pixel value');
  for (const mode of responsiveSpec.modes) {
    if (mode.maxExclusive === null || width < mode.maxExclusive) return mode.id;
  }
  throw new RangeError('No layout mode for width');
}
export function getContainerMode(width: number): 'compact' | 'standard' | 'workspace' {
  if (!Number.isFinite(width) || width < 0)
    throw new RangeError('Width must be a finite non-negative CSS pixel value');
  return width < responsiveSpec.componentContainers.standardMinPx
    ? 'compact'
    : width < responsiveSpec.componentContainers.workspaceMinPx
      ? 'standard'
      : 'workspace';
}
