import { z } from 'zod';
import { idSchema, instantSchema, localDateSchema, timeZoneSchema } from './primitives.js';
import { activityDetailsSchema } from './activity-details.js';

const boundedMetric = z.number().finite().nonnegative().max(1_000_000_000).nullable();
/** User-local labels. Normalize Unicode/outer whitespace; case remains significant. */
export const activityTagSchema = z
  .string()
  .transform((value) => value.trim().normalize('NFC'))
  .pipe(
    z
      .string()
      .min(1)
      .max(40)
      .regex(/^[^\p{Cc}\p{Cf}\p{Zl}\p{Zp}]+$/u),
  );
export const activityTagsSchema = z
  .array(activityTagSchema)
  .max(20)
  .refine((tags) => new Set(tags).size === tags.length, 'Duplicate local tags');
export const activityValuesSchema = z.strictObject({
  title: z.string().trim().min(1).max(200).nullable(),
  kind: z.enum(['running', 'cycling', 'walking', 'strength', 'other', 'unknown']),
  startedAt: z.iso.datetime({ offset: true }).nullable(),
  durationSeconds: boundedMetric,
  durationKind: z.enum(['timer', 'elapsed', 'moving', 'unknown']),
  timezone: timeZoneSchema.nullable(),
  distanceMeters: boundedMetric,
});
export const activitySourceSchema = z.strictObject({
  kind: z.enum(['fit', 'fixture', 'manual']),
  sourceId: z
    .string()
    .min(1)
    .max(200)
    .refine((value) => value.trim() === value),
  revision: z.number().int().min(1).max(2147483646),
  contentHash: z.string().regex(/^[a-f0-9]{64}$/),
});
/** Manual provenance can only be generated by the manual create command. */
export const importActivitySourceSchema = activitySourceSchema.extend({
  kind: z.enum(['fit', 'fixture']),
});
export const importActivitySchema = z.strictObject({
  idempotencyKey: z
    .string()
    .min(8)
    .max(128)
    .regex(/^[a-zA-Z0-9_-]+$/),
  source: importActivitySourceSchema,
  activity: activityValuesSchema,
  // Omission preserves the hash of legacy summary-only import commands.
  details: activityDetailsSchema.optional(),
});
export const activityExportSchema = z.discriminatedUnion('schemaVersion', [
  z.strictObject({
    schemaVersion: z.literal(1),
    imports: z
      .array(importActivitySchema.extend({ details: z.never().optional() }))
      .min(1)
      .max(100),
  }),
  z.strictObject({
    schemaVersion: z.literal(2),
    imports: z
      .array(importActivitySchema.extend({ details: activityDetailsSchema }))
      .min(1)
      .max(100),
  }),
]);
export const activityDetailsReadSchema = z.strictObject({
  activityId: z.uuid(),
  activityRevision: z.number().int().positive(),
  source: activitySourceSchema,
  details: activityDetailsSchema.nullable(),
});
export type ActivityDetailsRead = z.infer<typeof activityDetailsReadSchema>;
export const activityReportValuesSchema = z.strictObject({
  sessionRpe: z.number().finite().min(0).max(10).nullable(),
  note: z.string().trim().min(1).max(4000).nullable(),
  planLink: z.strictObject({ planVersionId: z.uuid(), sessionId: idSchema.max(200) }).nullable(),
});
export const activityReportSchema = activityReportValuesSchema
  .extend({
    definitionVersion: z.literal('activity-report-v1'),
    source: z.literal('user'),
    method: z.literal('self_report'),
    rpeReportedAt: instantSchema.nullable(),
  })
  .refine((report) => (report.sessionRpe === null) === (report.rpeReportedAt === null));
export const manualActivityCreateSchema = z.strictObject({
  confirmed: z.literal(true),
  activity: activityValuesSchema.extend({
    title: activityValuesSchema.shape.title.unwrap(),
    startedAt: instantSchema.refine((value) => value.slice(0, 4) !== '0000'),
    timezone: timeZoneSchema,
  }),
  report: activityReportValuesSchema,
  idempotencyKey: importActivitySchema.shape.idempotencyKey,
});
export const manualActivityResultSchema = z.strictObject({
  activityId: z.uuid(),
  revision: z.number().int().positive(),
});
const overlayFields = {
  title: activityValuesSchema.shape.title.optional(),
  kind: activityValuesSchema.shape.kind.optional(),
  startedAt: activityValuesSchema.shape.startedAt
    .refine((value) => value === null || value.slice(0, 4) !== '0000')
    .optional(),
  timezone: activityValuesSchema.shape.timezone.optional(),
  distanceMeters: boundedMetric.optional(),
  durationSeconds: boundedMetric.optional(),
  durationKind: activityValuesSchema.shape.durationKind.optional(),
  reason: z.string().trim().min(1).max(500).optional(),
  // Missing preserves legacy data; [] explicitly clears user-local tags.
  tags: activityTagsSchema.optional(),
};
const pairedOverlayFields = (value: {
  durationSeconds?: number | null | undefined;
  durationKind?: string | undefined;
  startedAt?: string | null | undefined;
  timezone?: string | null | undefined;
}) =>
  (value.durationSeconds !== undefined) === (value.durationKind !== undefined) &&
  (value.startedAt !== undefined) === (value.timezone !== undefined);
export const activityOverlaySchema = z
  .strictObject({
    ...overlayFields,
    userReport: activityReportSchema.optional(),
  })
  .refine(pairedOverlayFields, 'Correct time values together with their definitions');
export const activityOverlayWriteSchema = z
  .strictObject({
    ...overlayFields,
    report: activityReportValuesSchema.optional(),
    expectedRevision: z.number().int().min(1).max(2147483646),
    idempotencyKey: importActivitySchema.shape.idempotencyKey,
    reason: z.string().trim().min(1).max(500),
  })
  .refine(pairedOverlayFields, 'Correct time values together with their definitions')
  .refine(
    (value) =>
      value.title !== undefined ||
      value.kind !== undefined ||
      value.startedAt !== undefined ||
      value.distanceMeters !== undefined ||
      value.durationSeconds !== undefined ||
      value.tags !== undefined ||
      value.report !== undefined,
  );
export const activityDeleteSchema = z.strictObject({
  expectedRevision: z.number().int().min(1).max(2147483646),
});
export const activitySchema = z.strictObject({
  id: z.uuid(),
  revision: z.number().int().positive(),
  source: activitySourceSchema,
  original: activityValuesSchema,
  overlay: activityOverlaySchema,
  effective: activityValuesSchema,
  // Omission in older JSON/receipts means no stored report; never substitute RPE zero.
  userReport: activityReportSchema.nullable().optional(),
});
const activityFilterDateSchema = localDateSchema.refine((value) => value >= '0001-01-01');
export const activityListQuerySchema = z
  .strictObject({
    limit: z.coerce.number().int().min(1).max(100).default(50),
    offset: z.coerce.number().int().min(0).max(10_000).default(0),
    from: activityFilterDateSchema.optional(),
    toExclusive: activityFilterDateSchema.optional(),
    timezone: timeZoneSchema.optional(),
    kind: activityValuesSchema.shape.kind.optional(),
    source: activitySourceSchema.shape.kind.optional(),
    // Current effective values and explicit user correction, never a quality score.
    quality: z
      .enum(['missing_distance', 'missing_duration', 'missing_start', 'corrected'])
      .optional(),
    search: z.string().trim().min(1).max(200).optional(),
    tag: activityTagSchema.optional(),
    linkedPlanVersionId: z.uuid().optional(),
    linkedBlockId: idSchema.optional(),
    sort: z
      .enum(['id_asc', 'started_desc', 'started_asc', 'distance_desc', 'distance_asc', 'title_asc'])
      .optional(),
  })
  .refine(
    ({ linkedPlanVersionId, linkedBlockId }) =>
      (linkedPlanVersionId === undefined) === (linkedBlockId === undefined),
    { message: 'Linked Block filtering requires both a plan version and a Block ID' },
  )
  .refine(
    ({ from, toExclusive, timezone }) => {
      if (from === undefined && toExclusive === undefined && timezone === undefined) return true;
      if (from === undefined || toExclusive === undefined || timezone === undefined) return false;
      const days =
        (Date.parse(`${toExclusive}T00:00:00Z`) - Date.parse(`${from}T00:00:00Z`)) / 86_400_000;
      return days >= 1 && days <= 3660;
    },
    { message: 'Date filtering requires a timezone and a 1–3660 calendar-day range' },
  );
export const activityListSchema = z.strictObject({
  items: z.array(activitySchema).max(100),
  total: z.number().int().nonnegative(),
});
export const activityImportResultSchema = z.strictObject({
  outcome: z.enum(['imported', 'unchanged', 'stale', 'suppressed']),
  activityId: z.uuid(),
  revision: z.number().int().positive(),
});
const aggregateSchema = z.strictObject({
  value: z.number().nonnegative().nullable(),
  knownCount: z.number().int().nonnegative(),
});
export const activitySummarySchema = z.strictObject({
  count: z.number().int().nonnegative(),
  distanceMeters: aggregateSchema,
  durationSeconds: aggregateSchema.extend({
    byKind: z.strictObject({
      timer: aggregateSchema,
      elapsed: aggregateSchema,
      moving: aggregateSchema,
      unknown: aggregateSchema,
    }),
  }),
});
export type Activity = z.infer<typeof activitySchema>;
export type ActivityImport = z.infer<typeof importActivitySchema>;
export type ActivityImportResult = z.infer<typeof activityImportResultSchema>;
export type ActivityList = z.infer<typeof activityListSchema>;
export type ActivityListQuery = z.infer<typeof activityListQuerySchema>;
export type ActivitySummary = z.infer<typeof activitySummarySchema>;
export type ActivityOverlayWrite = z.infer<typeof activityOverlayWriteSchema>;
export type ActivityReportValues = z.infer<typeof activityReportValuesSchema>;
export type ActivityReport = z.infer<typeof activityReportSchema>;
export type ManualActivityCreate = z.infer<typeof manualActivityCreateSchema>;
export type ManualActivityResult = z.infer<typeof manualActivityResultSchema>;
