import { createHash } from 'node:crypto';

import {
  courseLimits,
  targetDistanceLimits,
  type CourseCandidateEvaluation,
  type CourseCandidateSearchSummary,
  type CoursePosition,
  type CourseWaypoint,
} from '@workout/contracts/courses';
import type { RouteComputationRecord, RoutingPosition } from '@workout/contracts/routing';

import { greatCircleMeters } from './geo.js';

/**
 * Bounded target-distance candidate search (M2-01i).
 *
 * WHAT THIS IS, AND WHAT IT IS NOT.
 *
 * A target distance is an approximation. This module generates a small, bounded number of
 * **proposals** for one: it picks loop shapes from a recorded seed, asks our own pedestrian
 * engine to route each of them, measures what came back and offers only the ones that are
 * close enough to be worth looking at. Nothing it produces is saved, approved, or a course.
 * The owner picks one, and only that pick writes anything.
 *
 * WHY IT COMPOSES ROUTED LEGS INSTEAD OF CALLING THE ENGINE'S ROUND TRIP.
 *
 * GraphHopper does have `algorithm=round_trip` (M2-01d measured it: 4,428.763 m for a
 * 5,000 m target). It is not used here, and the reason is a guard rather than a preference.
 * M2-01g refuses any engine answer that does not attest the graph edges behind it, that
 * does not start at the first snapped waypoint, end at the last and visit the rest **in the
 * requested order**. A round trip's waypoints are generated by the engine, so that order
 * check has nothing to check against and would have to be relaxed — which would weaken the
 * exact defence that keeps a fallback straight line from being reported as success. Instead
 * every candidate here is built from waypoints WE chose, routed through the ordinary
 * bounded path, and therefore every leg of every candidate has already passed that guard
 * unchanged. The plan allows either the engine's round trip or our own bounded search; this
 * is the second, and it costs nothing in safety.
 *
 * EVERYTHING IS BOUNDED AND RECORDED. Candidates, attempts, wall-clock time and the
 * geographic radius all have ceilings ({@link targetDistanceLimits}), the seed of the search
 * and of each attempt is recorded so the same search can be run again, and the evaluation
 * version travels with every candidate. The attempt log keeps the rejected attempts too: a
 * reader has to be able to see that eight computations produced two candidates.
 *
 * NOTHING HERE JUDGES PASSABILITY. The engine answering means a graph had edges. It is not
 * evidence about stairs, surface, opening hours or access restrictions — we have no such
 * data in this build, and {@link CourseCandidateEvaluation}'s `knowledge` says `unknown`
 * for each of them rather than treating a missing fact as satisfied.
 */
export class CandidateSearchError extends Error {
  constructor(
    readonly code:
      | 'CANDIDATE_TOO_MANY_LOCKED_WAYPOINTS'
      | 'CANDIDATE_LOCKED_WAYPOINTS_EXCEED_TARGET'
      | 'CANDIDATE_LOCKED_WAYPOINT_OUTSIDE_SEARCH_AREA'
      | 'CANDIDATE_LOCKED_FINISH_NOT_A_LOOP'
      | 'CANDIDATE_WAYPOINT_COUNT_MISMATCH'
      | 'CANDIDATE_START_MISSING'
      | 'CANDIDATE_TARGET_OUT_OF_RANGE',
  ) {
    super(code);
    this.name = 'CandidateSearchError';
  }
}

/**
 * The first radius to try, as a share of the distance still to cover.
 *
 * A candidate is a triangle whose first vertex is the origin and whose other two sit at
 * one radius from it, 120 degrees apart: the straight-line perimeter is therefore
 * `r + 2r·sin(60°) + r = (2 + √3)·r`. Starting from that share puts the first attempt near
 * the target before the search has measured anything; every later attempt is steered by
 * what the engine actually answered, because a walked route is longer than its chords.
 */
const TRIANGLE_RADIUS_RATIO = 1 / (2 + Math.sqrt(3));
/** Generated points per attempt, on top of the origin and any locked waypoints. */
const GENERATED_POINTS = 2;
/** Repeated share at or above which a loop is reported as an out-and-back. */
const OUT_AND_BACK_RATIO = 0.4;
/** A failure that says the engine or the tenant bound stopped us, not this shape. */
const TERMINAL_OUTCOMES = new Set([
  'cancelled',
  'overloaded',
  'timeout',
  'engine_unavailable',
  'graph_mismatch',
]);

export type CandidateRouteOutcome =
  | 'no_route'
  | 'outside_coverage'
  | 'snap_too_far'
  | 'timeout'
  | 'cancelled'
  | 'overloaded'
  | 'compute_budget_exceeded'
  | 'engine_unavailable'
  | 'engine_contract_violation'
  | 'graph_mismatch'
  | 'request_refused';

export interface CandidateSnappedWaypoint {
  readonly requested: RoutingPosition;
  readonly snapped: RoutingPosition;
  readonly snapDistanceMeters: number;
}

export type CandidateRouteAnswer =
  | {
      readonly kind: 'computed';
      readonly coordinates: readonly CoursePosition[];
      readonly distanceMeters: number;
      readonly durationSeconds: number;
      readonly snappedWaypoints: readonly CandidateSnappedWaypoint[];
      readonly computation: RouteComputationRecord;
    }
  | {
      readonly kind: 'refused';
      readonly outcome: CandidateRouteOutcome;
      /** `null` when the engine was never reached, which is a different fact. */
      readonly computation: RouteComputationRecord | null;
    };

/**
 * The one way this search reaches the engine. It is the ordinary bounded walking-route
 * path — the same admission control, the same deadline, the same answer validation — so
 * this module cannot route around any of it.
 */
export interface CandidateLegRouter {
  route(
    input: {
      readonly requestId: string;
      readonly requestRevision: number;
      readonly waypoints: readonly CoursePosition[];
    },
    /**
     * Aborted when the whole search runs out of budget or the caller goes away. Honouring
     * it is what makes the search budget a bound on the search rather than a bound on the
     * gaps between its calls.
     */
    context: { readonly signal: AbortSignal },
  ): Promise<CandidateRouteAnswer>;
}

/**
 * How the search arms its own deadline. Injected so a test can fire it against a fake
 * clock instead of waiting: a budget that only real time can enforce is a budget no test
 * can hold in place.
 */
export interface CandidateDeadlineScheduler {
  schedule(onDeadline: () => void, delayMilliseconds: number): () => void;
}

const realDeadlineScheduler: CandidateDeadlineScheduler = {
  schedule(onDeadline, delayMilliseconds) {
    const timer = setTimeout(onDeadline, Math.max(0, delayMilliseconds));
    return () => clearTimeout(timer);
  },
};

export interface CandidateSearchClock {
  now(): Date;
}

export interface GeneratedCandidate {
  readonly attemptIndex: number;
  readonly candidateSeed: string;
  readonly waypoints: readonly CourseWaypoint[];
  readonly coordinates: readonly CoursePosition[];
  readonly engineDistanceMeters: number;
  readonly engineDurationSeconds: number;
  readonly snappedWaypoints: readonly CandidateSnappedWaypoint[];
  readonly computation: RouteComputationRecord;
  readonly evaluation: CourseCandidateEvaluation;
}

export interface CandidateSearchResult {
  readonly candidates: readonly GeneratedCandidate[];
  readonly search: CourseCandidateSearchSummary;
  /** Effective bounds this run used, reported so the answer says what it was allowed. */
  readonly bounds: {
    readonly maxCandidates: number;
    readonly maxAttempts: number;
    readonly searchBudgetMilliseconds: number;
    readonly maxSearchRadiusMeters: number;
    readonly distanceToleranceRatio: number;
  };
  /** The last computation that actually reached the engine, or `null` if none did. */
  readonly lastComputation: RouteComputationRecord | null;
  /**
   * Set only when the search stopped because the engine or a tenant bound refused it. A
   * refusal is not the same fact as "we looked and found nothing"; the caller answers them
   * with different outcomes and different status codes.
   */
  readonly terminalOutcome: CandidateRouteOutcome | null;
}

export interface CandidateSearchInput {
  readonly requestId: string;
  readonly draftRevision: number;
  readonly targetDistanceMeters: number;
  /** 16 hex characters. The caller records it; replaying it reruns the same search. */
  readonly searchSeed: string;
  readonly waypoints: readonly CourseWaypoint[];
  readonly router: CandidateLegRouter;
  readonly clock: CandidateSearchClock;
  readonly signal?: AbortSignal;
  readonly deadline?: CandidateDeadlineScheduler;
}

const EARTH_RADIUS_METERS = 6_371_008.8;
const toRadians = (degrees: number): number => (degrees * Math.PI) / 180;
const toDegrees = (radians: number): number => (radians * 180) / Math.PI;

/** Great-circle forward: where you land going `bearing` degrees for `distance` metres. */
export function destinationPoint(
  origin: CoursePosition,
  bearingDegrees: number,
  distanceMeters: number,
): CoursePosition {
  const angular = distanceMeters / EARTH_RADIUS_METERS;
  const bearing = toRadians(bearingDegrees);
  const latitude = toRadians(origin[1]);
  const longitude = toRadians(origin[0]);
  const sinLatitude =
    Math.sin(latitude) * Math.cos(angular) +
    Math.cos(latitude) * Math.sin(angular) * Math.cos(bearing);
  const nextLatitude = Math.asin(Math.min(1, Math.max(-1, sinLatitude)));
  const nextLongitude =
    longitude +
    Math.atan2(
      Math.sin(bearing) * Math.sin(angular) * Math.cos(latitude),
      Math.cos(angular) - Math.sin(latitude) * Math.sin(nextLatitude),
    );
  // Wrapped rather than clamped: a search near the antimeridian must not be silently
  // folded back onto a different meridian.
  const degrees = toDegrees(nextLongitude);
  const wrapped = ((((degrees + 180) % 360) + 360) % 360) - 180;
  return [wrapped, toDegrees(nextLatitude)];
}

/**
 * The seed of one attempt, derived from the search seed. Deterministic on purpose: the
 * recorded seed and the attempt index are enough to reproduce exactly this attempt.
 */
export function deriveCandidateSeed(searchSeed: string, attemptIndex: number): string {
  return createHash('sha256')
    .update(`target-distance-loop-v1:${searchSeed}:${attemptIndex}`)
    .digest('hex')
    .slice(0, 16);
}

/** A small deterministic generator. Not cryptographic; it only has to be reproducible. */
function generatorFromSeed(seed: string): () => number {
  let state = 0;
  for (const character of seed) state = (state * 33 + character.charCodeAt(0)) >>> 0;
  return () => {
    // xorshift32; the same seed always yields the same sequence on every runtime.
    state ^= state << 13;
    state >>>= 0;
    state ^= state >>> 17;
    state ^= state << 5;
    state >>>= 0;
    return state / 0x1_0000_0000;
  };
}

function roundedKey(position: CoursePosition): string {
  const grid = targetDistanceLimits.sectionGridDegrees;
  return `${Math.round(position[0] / grid)}:${Math.round(position[1] / grid)}`;
}

/**
 * Distance between samples when a line is walked cell by cell. Half the grid cell at this
 * latitude, so a step can never jump over a cell it passed through.
 */
const TRAVERSAL_SAMPLE_METERS = 2;
/** Upper bound on the samples one line may cost. Beyond it the step grows instead. */
const MAX_TRAVERSAL_SAMPLES = 200_000;

export interface CellTraversal {
  /** Metres of this line that lie inside the cell. */
  readonly meters: number;
  /** How many separate times the line entered the cell. Two means it came back. */
  readonly visits: number;
}

/**
 * Which ground a line actually covers, and how often.
 *
 * WHY THIS IS NOT A COMPARISON OF VERTEX PAIRS. The first version keyed adjacent vertex
 * pairs, and that made the answer depend on where the engine happened to put its vertices:
 * `A → B` and `A → mid → B` are the same walk but shared **nothing**, and a full
 * out-and-back that returned through one extra vertex reported **no** repetition at all.
 * Vertices are an encoding of a line, not the line. So the line is walked at a fixed step
 * and attributed to fixed grid cells: two encodings of the same walk produce the same cells
 * with the same metres, and a walk that covers the same ground twice visits its cells twice
 * however it is split.
 */
export function traversedCells(coordinates: readonly CoursePosition[]): Map<string, CellTraversal> {
  const cells = new Map<string, { meters: number; visits: number }>();
  const total = polylineMeters(coordinates);
  if (total <= 0 || coordinates.length < 2) return cells;
  const step = Math.max(TRAVERSAL_SAMPLE_METERS, total / MAX_TRAVERSAL_SAMPLES);
  let previousCell: string | null = null;
  const enter = (key: string, meters: number) => {
    const existing = cells.get(key);
    if (existing === undefined) cells.set(key, { meters, visits: 1 });
    else {
      existing.meters += meters;
      // A new visit only when the walk had left the cell in between.
      if (previousCell !== key) existing.visits += 1;
    }
    previousCell = key;
  };
  for (let index = 1; index < coordinates.length; index += 1) {
    const from = coordinates[index - 1];
    const to = coordinates[index];
    if (from === undefined || to === undefined) continue;
    const length = greatCircleMeters(from, to);
    if (length <= 0) continue;
    const steps = Math.max(1, Math.ceil(length / step));
    const share = length / steps;
    for (let piece = 0; piece < steps; piece += 1) {
      // The cell of the middle of this piece, so a piece is attributed to the cell it is in
      // rather than to the one it started on the edge of.
      const t = (piece + 0.5) / steps;
      enter(roundedKey([from[0] + (to[0] - from[0]) * t, from[1] + (to[1] - from[1]) * t]), share);
    }
  }
  return cells;
}

export function polylineMeters(coordinates: readonly CoursePosition[]): number {
  let total = 0;
  for (let index = 1; index < coordinates.length; index += 1) {
    const previous = coordinates[index - 1];
    const current = coordinates[index];
    if (previous === undefined || current === undefined) continue;
    total += greatCircleMeters(previous, current);
  }
  return total;
}

/**
 * How much of a line is walked more than once.
 *
 * A cell entered `v` times holds `v` passes over the same ground, so `(v-1)/v` of the metres
 * inside it are repetition. A perfect out-and-back therefore reports half the line, whatever
 * vertices it was encoded with. A closed loop reports the small overlap at the point where
 * it rejoins itself, which is a true fact about it and is left visible rather than special-cased.
 */
export function repeatedSection(coordinates: readonly CoursePosition[]): {
  readonly repeatedMeters: number;
  readonly repeatedRatio: number;
  readonly outAndBack: boolean;
} {
  const cells = traversedCells(coordinates);
  let repeatedMeters = 0;
  for (const cell of cells.values())
    if (cell.visits > 1) repeatedMeters += (cell.meters * (cell.visits - 1)) / cell.visits;
  const total = polylineMeters(coordinates);
  const repeatedRatio = total > 0 ? Math.min(1, repeatedMeters / total) : 0;
  return { repeatedMeters, repeatedRatio, outAndBack: repeatedRatio >= OUT_AND_BACK_RATIO };
}

/**
 * Shared ground between two lines, as a share of the shorter one. Two candidates that run
 * over mostly the same streets are one proposal, not two, and offering both would pretend
 * the search found more than it did. Split-independent for the same reason as above: the
 * same walk encoded with different vertices is the same walk.
 */
export function shapeOverlapRatio(
  left: readonly CoursePosition[],
  right: readonly CoursePosition[],
): number {
  return cellOverlapRatio(traversedCells(left), traversedCells(right));
}

/**
 * The same comparison over cells that have already been walked. The search keeps the cells
 * of every candidate it accepted, so a line is walked once however many candidates it is
 * compared against.
 */
export function cellOverlapRatio(
  a: Map<string, CellTraversal>,
  b: Map<string, CellTraversal>,
): number {
  let shared = 0;
  let totalA = 0;
  for (const [key, cell] of a) {
    totalA += cell.meters;
    const other = b.get(key);
    if (other !== undefined) shared += Math.min(cell.meters, other.meters);
  }
  let totalB = 0;
  for (const cell of b.values()) totalB += cell.meters;
  const smaller = Math.min(totalA, totalB);
  return smaller > 0 ? Math.min(1, shared / smaller) : 0;
}

function maxSnap(snapped: readonly CandidateSnappedWaypoint[]): number {
  let furthest = 0;
  for (const waypoint of snapped) furthest = Math.max(furthest, waypoint.snapDistanceMeters);
  return furthest;
}

function evaluate(input: {
  readonly targetDistanceMeters: number;
  readonly coordinates: readonly CoursePosition[];
  readonly engineDistanceMeters: number;
  readonly snappedWaypoints: readonly CandidateSnappedWaypoint[];
  readonly waypointCount: number;
}): CourseCandidateEvaluation {
  const first = input.coordinates[0];
  const last = input.coordinates[input.coordinates.length - 1];
  const gapMeters = first && last ? greatCircleMeters(first, last) : Number.POSITIVE_INFINITY;
  const repetition = repeatedSection(input.coordinates);
  const error = input.engineDistanceMeters - input.targetDistanceMeters;
  return {
    evaluationVersion: 1,
    targetDistanceMeters: input.targetDistanceMeters,
    engineDistanceMeters: input.engineDistanceMeters,
    plannedLineMeters: polylineMeters(input.coordinates),
    distanceErrorMeters: error,
    distanceErrorRatio: error / input.targetDistanceMeters,
    loop: {
      closed: gapMeters <= targetDistanceLimits.loopClosureMeters,
      gapMeters: Number.isFinite(gapMeters) ? gapMeters : 1_000_000,
    },
    connectivity: 'engine-attested-edges',
    repetition,
    // Not a shortcut: this build has no surface, stair, opening-hour or elevation data at
    // all, and the plan forbids reading a missing fact as a satisfied one.
    knowledge: {
      stairs: 'unknown',
      surface: 'unknown',
      nightAccess: 'unknown',
      accessRestrictions: 'unknown',
      gradient: 'unknown',
    },
    gradientSource: 'none',
    maxSnapDistanceMeters: maxSnap(input.snappedWaypoints),
    waypointCount: input.waypointCount,
    vertexCount: input.coordinates.length,
  };
}

/** The radius this search is allowed to wander in, from the target and the hard cap. */
export function searchRadiusMeters(targetDistanceMeters: number): number {
  return Math.min(
    targetDistanceLimits.maxSearchRadiusMeters,
    Math.max(1_000, targetDistanceMeters * 0.5),
  );
}

export async function generateTargetDistanceCandidates(
  input: CandidateSearchInput,
): Promise<CandidateSearchResult> {
  const target = input.targetDistanceMeters;
  if (
    !Number.isFinite(target) ||
    target < targetDistanceLimits.minTargetMeters ||
    target > targetDistanceLimits.maxTargetMeters
  )
    throw new CandidateSearchError('CANDIDATE_TARGET_OUT_OF_RANGE');

  const start = input.waypoints[0];
  if (start === undefined) throw new CandidateSearchError('CANDIDATE_START_MISSING');
  const origin = start.position;
  // Locked waypoints are the owner's pins. The search keeps them, in order, and never
  // moves or drops one: a generated candidate that quietly lost a pinned point would be a
  // different route from the one that was asked for.
  const locked = input.waypoints.slice(1, -1).filter((waypoint) => waypoint.locked);
  if (locked.length + GENERATED_POINTS + 2 > courseLimits.waypoints)
    throw new CandidateSearchError('CANDIDATE_TOO_MANY_LOCKED_WAYPOINTS');
  // A loop comes back to where it started, so a pinned finish somewhere else is not a
  // constraint this search can satisfy. It used to be dropped in silence — `slice(1, -1)`
  // never looked at it — and every candidate was built with a finish the owner had not
  // asked for. A lock is a refusal, not a suggestion: say so and change nothing.
  const declaredFinish = input.waypoints[input.waypoints.length - 1];
  const lockedFinish =
    declaredFinish !== undefined && declaredFinish !== start && declaredFinish.locked
      ? declaredFinish
      : null;
  if (
    lockedFinish !== null &&
    greatCircleMeters(origin, lockedFinish.position) > targetDistanceLimits.loopClosureMeters
  )
    throw new CandidateSearchError('CANDIDATE_LOCKED_FINISH_NOT_A_LOOP');

  const radiusCap = searchRadiusMeters(target);
  let lockedStraight = 0;
  let cursor = origin;
  for (const waypoint of locked) {
    if (greatCircleMeters(origin, waypoint.position) > radiusCap)
      throw new CandidateSearchError('CANDIDATE_LOCKED_WAYPOINT_OUTSIDE_SEARCH_AREA');
    lockedStraight += greatCircleMeters(cursor, waypoint.position);
    cursor = waypoint.position;
  }
  lockedStraight += greatCircleMeters(cursor, origin);
  if (lockedStraight > target * (1 + targetDistanceLimits.distanceToleranceRatio))
    throw new CandidateSearchError('CANDIDATE_LOCKED_WAYPOINTS_EXCEED_TARGET');

  const bounds = {
    maxCandidates: targetDistanceLimits.maxCandidates,
    maxAttempts: targetDistanceLimits.maxAttempts,
    searchBudgetMilliseconds: targetDistanceLimits.searchBudgetMilliseconds,
    maxSearchRadiusMeters: radiusCap,
    distanceToleranceRatio: targetDistanceLimits.distanceToleranceRatio,
  } as const;

  const startedAt = input.clock.now().getTime();
  const attempts: CourseCandidateSearchSummary['attempts'] = [];
  const accepted: GeneratedCandidate[] = [];
  const acceptedCells: Map<string, CellTraversal>[] = [];
  let duplicatesDropped = 0;
  let lastComputation: RouteComputationRecord | null = null;
  let terminalOutcome: CandidateRouteOutcome | null = null;
  let stoppedBecause: CourseCandidateSearchSummary['stoppedBecause'] = 'attempt_limit';
  // The remaining budget after the legs the owner pinned. A loop through pins is shorter
  // than the target by that much, so the generated part must be smaller too.
  const remaining = Math.max(target - lockedStraight, target * 0.1);
  let radius = Math.min(radiusCap, remaining * TRIANGLE_RADIUS_RATIO);

  const deadlineAt = startedAt + bounds.searchBudgetMilliseconds;
  const scheduler = input.deadline ?? realDeadlineScheduler;
  const elapsed = () => Math.max(0, input.clock.now().getTime() - startedAt);
  const outOfBudget = () => input.clock.now().getTime() >= deadlineAt;
  const callerCancelled = () => input.signal?.aborted === true;

  for (let attemptIndex = 0; attemptIndex < bounds.maxAttempts; attemptIndex += 1) {
    if (accepted.length >= bounds.maxCandidates) {
      stoppedBecause = 'candidate_limit';
      break;
    }
    if (callerCancelled()) {
      stoppedBecause = 'cancelled';
      terminalOutcome = 'cancelled';
      break;
    }
    if (outOfBudget()) {
      stoppedBecause = 'time_budget';
      break;
    }
    const candidateSeed = deriveCandidateSeed(input.searchSeed, attemptIndex);
    const random = generatorFromSeed(candidateSeed);
    const bearing = random() * 360;
    const spread = 120 + (random() - 0.5) * 50;
    const requestedRadius = Math.min(radiusCap, Math.max(50, radius));
    const generated = [
      destinationPoint(origin, bearing, requestedRadius),
      destinationPoint(origin, bearing + spread, requestedRadius),
    ];
    const waypoints: CourseWaypoint[] = [
      { ...start, role: 'start' },
      ...locked.map((waypoint) => ({ ...waypoint, role: 'via' as const })),
      ...generated.map((position) => ({
        role: 'via' as const,
        position,
        name: null,
        sourceSampleId: null,
        locked: false,
      })),
      // A finish the owner pinned at the origin is compatible with a loop, so it is kept
      // exactly as they left it. Otherwise the closing point is a generated return to the
      // origin, not the observation the start came from — claiming that sample for it
      // would be a second claim on one recorded position.
      lockedFinish ?? {
        role: 'finish' as const,
        position: origin,
        name: start.name,
        sourceSampleId: null,
        locked: false,
      },
    ];

    // The remaining whole-search budget is handed to the call itself. Checking the budget
    // only between calls bounded the gaps and not the search: eight calls each finishing
    // just inside the per-call limit ran well past the budget this answer reports. Now the
    // call is aborted when the budget runs out, and an answer that arrives after it is not
    // used — a late answer is not a free one.
    const controller = new AbortController();
    let deadlineReached = false;
    const onCallerAbort = () => controller.abort();
    input.signal?.addEventListener('abort', onCallerAbort, { once: true });
    if (callerCancelled()) controller.abort();
    const cancelDeadline = scheduler.schedule(
      () => {
        deadlineReached = true;
        controller.abort();
      },
      Math.max(0, deadlineAt - input.clock.now().getTime()),
    );
    let answer: CandidateRouteAnswer;
    try {
      answer = await input.router.route(
        {
          requestId: `${input.requestId}:${attemptIndex}`,
          requestRevision: input.draftRevision,
          waypoints: waypoints.map((waypoint) => waypoint.position),
        },
        { signal: controller.signal },
      );
    } finally {
      cancelDeadline();
      input.signal?.removeEventListener('abort', onCallerAbort);
    }
    if (answer.kind === 'refused' && answer.computation !== null)
      lastComputation = answer.computation;
    else if (answer.kind === 'computed') lastComputation = answer.computation;
    // The caller going away is a different fact from our own budget running out, and an
    // abort looks the same from the adapter either way. Ask who asked.
    if (callerCancelled()) {
      attempts.push({
        attemptIndex,
        candidateSeed,
        requestedRadiusMeters: requestedRadius,
        outcome: 'cancelled',
        engineDistanceMeters: null,
      });
      stoppedBecause = 'cancelled';
      terminalOutcome = 'cancelled';
      break;
    }
    if (deadlineReached || outOfBudget()) {
      attempts.push({
        attemptIndex,
        candidateSeed,
        requestedRadiusMeters: requestedRadius,
        // The search stopped because it ran out of its own time, which is a bound being
        // reached rather than an unknown result: nothing was stored either way.
        outcome: 'timeout',
        engineDistanceMeters: answer.kind === 'computed' ? answer.distanceMeters : null,
      });
      stoppedBecause = 'time_budget';
      break;
    }
    if (answer.kind === 'refused') {
      attempts.push({
        attemptIndex,
        candidateSeed,
        requestedRadiusMeters: requestedRadius,
        outcome: answer.outcome,
        engineDistanceMeters: null,
      });
      if (TERMINAL_OUTCOMES.has(answer.outcome)) {
        terminalOutcome = answer.outcome;
        stoppedBecause = answer.outcome === 'cancelled' ? 'cancelled' : 'engine_refusal';
        break;
      }
      continue;
    }
    // Steer the next attempt by what this one measured. Bounded on both sides so one
    // strange answer cannot send the search outside the radius it is allowed.
    if (answer.distanceMeters > 0)
      radius = Math.min(
        radiusCap,
        Math.max(
          remaining * 0.02,
          Math.min(remaining * 0.5, radius * (target / answer.distanceMeters)),
        ),
      );

    const outside = answer.coordinates.some(
      (position) => greatCircleMeters(origin, position) > radiusCap,
    );
    if (outside) {
      attempts.push({
        attemptIndex,
        candidateSeed,
        requestedRadiusMeters: requestedRadius,
        outcome: 'outside_search_area',
        engineDistanceMeters: answer.distanceMeters,
      });
      continue;
    }
    const evaluation = evaluate({
      targetDistanceMeters: target,
      coordinates: answer.coordinates,
      engineDistanceMeters: answer.distanceMeters,
      snappedWaypoints: answer.snappedWaypoints,
      waypointCount: waypoints.length,
    });
    if (!evaluation.loop.closed) {
      attempts.push({
        attemptIndex,
        candidateSeed,
        requestedRadiusMeters: requestedRadius,
        outcome: 'not_a_loop',
        engineDistanceMeters: answer.distanceMeters,
      });
      continue;
    }
    if (Math.abs(evaluation.distanceErrorRatio) > bounds.distanceToleranceRatio) {
      attempts.push({
        attemptIndex,
        candidateSeed,
        requestedRadiusMeters: requestedRadius,
        outcome: 'off_target',
        engineDistanceMeters: answer.distanceMeters,
      });
      continue;
    }
    const answerCells = traversedCells(answer.coordinates);
    const duplicate = acceptedCells.some(
      (cells) => cellOverlapRatio(cells, answerCells) >= targetDistanceLimits.duplicateOverlapRatio,
    );
    if (duplicate) {
      duplicatesDropped += 1;
      attempts.push({
        attemptIndex,
        candidateSeed,
        requestedRadiusMeters: requestedRadius,
        outcome: 'duplicate',
        engineDistanceMeters: answer.distanceMeters,
      });
      continue;
    }
    acceptedCells.push(answerCells);
    accepted.push({
      attemptIndex,
      candidateSeed,
      waypoints,
      coordinates: answer.coordinates,
      engineDistanceMeters: answer.distanceMeters,
      engineDurationSeconds: answer.durationSeconds,
      snappedWaypoints: answer.snappedWaypoints,
      computation: answer.computation,
      evaluation,
    });
    attempts.push({
      attemptIndex,
      candidateSeed,
      requestedRadiusMeters: requestedRadius,
      outcome: 'accepted',
      engineDistanceMeters: answer.distanceMeters,
    });
    if (accepted.length >= bounds.maxCandidates) {
      stoppedBecause = 'candidate_limit';
      break;
    }
  }

  return {
    candidates: accepted,
    bounds,
    lastComputation,
    terminalOutcome,
    search: {
      attemptsMade: attempts.length,
      elapsedMilliseconds: Math.round(elapsed()),
      duplicatesDropped,
      attempts,
      stoppedBecause,
    },
  };
}

/**
 * Turn one picked candidate into the conditions its revision keeps.
 *
 * Like the routed conditions this carries no coordinate: the line belongs to the revision's
 * geometry and the waypoints to its waypoint list. What it adds is everything needed to run
 * the same search again — the target, both seeds, the attempt index, the generator version
 * — and the evaluation, so a stored course says how far off the target it actually is.
 */
export function targetDistanceGeneration(input: {
  readonly computation: RouteComputationRecord;
  readonly coordinates: readonly CoursePosition[];
  readonly waypoints: readonly CourseWaypoint[];
  readonly engineDistanceMeters: number;
  readonly engineDurationSeconds: number;
  readonly snappedWaypoints: readonly CandidateSnappedWaypoint[];
  readonly targetDistanceMeters: number;
  readonly searchSeed: string;
  readonly candidateSeed: string;
  readonly attemptIndex: number;
  readonly evaluation: CourseCandidateEvaluation;
}) {
  if (input.computation.conditions.waypointCount !== input.waypoints.length)
    throw new CandidateSearchError('CANDIDATE_WAYPOINT_COUNT_MISMATCH');
  if (input.snappedWaypoints.length !== input.waypoints.length)
    throw new CandidateSearchError('CANDIDATE_WAYPOINT_COUNT_MISMATCH');
  return {
    kind: 'target-distance-loop' as const,
    computation: input.computation,
    engineDistanceMeters: input.engineDistanceMeters,
    engineDurationSeconds: input.engineDurationSeconds,
    maxSnapDistanceMeters: maxSnap(input.snappedWaypoints),
    waypointCount: input.waypoints.length,
    vertexCount: input.coordinates.length,
    targetDistanceMeters: input.targetDistanceMeters,
    searchSeed: input.searchSeed,
    candidateSeed: input.candidateSeed,
    attemptIndex: input.attemptIndex,
    generatorVersion: 'target-distance-loop-v1' as const,
    evaluation: input.evaluation,
  };
}
